# nice name of the server config
title = "My Cool Server"

# actual server settings
[server]
gamemode = "sandbox" # the default gamemode
map = "gm_flatgrass" # the default map
maxplayers = 32 # the max player slots

# list of available maps
# this is merged with all maps keys below so duplication of values is not necessary (maps, addons[i].maps)
# this is not used by the server setup, it is useful if you need a list of maps and want it organized by addon/item
maps = [
	"gm_construct",
	"gm_flatgrass",
]

# github addon that will be cloned
[[addons]]
folder = "wire" # garrysmod/addons/wire
url = "https://github.com/Buildstruct/wire.git"
branch = "master" # only this branch will be cloned (if this is not set, all branches will be cloned and the default will be selected)

# workshop addon that will be downloaded
[[addons]]
id = 105982362
maps = ["gm_bigcity"]

[[addons]]
id = 815782148
maps = ["gm_bigcity_improved"]

[[addons]]
id = 123277559 # Nyan Gun
download = true # mark this item to be automatically downloaded by clients
