title = "Extreme Football Throwdown"

[server]
gamemode = "extremefootballthrowdown"
host_workshop_collection = 3613047573

[[addons]]
folder = "extremefootballthrowdown"
url = "https://github.com/JetBoom/extremefootballthrowdown.git"
branch = "master"

[[addons]]
id = 244859331 # Extreme Football Throwdown Map Pack
maps = [
	"eft_albino",
	"eft_big_metal03r1",
	"eft_bloodbowlb",
	"eft_brokenbonesbridge_v1fix",
	"eft_castle_warfare",
	"eft_chamber",
	"eft_coconutclub_01",
	"eft_handegg",
	"eft_minecraftv2fixed",
	"eft_sky_metal_beta3",
	"eft_skystep_v3",
	"eft_soccer_b1",
	"eft_spacejump_b2",
	"eft_temple_sacrifice_rc",
	"eft_tunnel",
	"eft_turbines_v2",
	"xft_skyline_v2",
]

[[addons]]
id = 189289375
maps = ["xft_skyteenagers_spartv"]

[[addons]]
id = 579589507
maps = ["eft_streetball_v6"]

[[addons]]
id = 493032732
maps = ["eft_hexa_v5"]
