title = "Half-Life Co-op"

[server]
gamemode = "hl1coop"
map = "hls00amrl"

[[addons]]
id = 1590755372 # Half-Life Co-op
gamemodes = ["hl1coop"]

[[addons]]
id = 971893221 # Half-Life Resized Maps

[[addons]]
id = 1360233031 # Half-Life SWEPS
download = true

[[addons]]
id = 1290525688 # GoldSrc HUD
download = true
