title = "Jazztronauts"

[server]
gamemode = "jazztronauts"
map = "jazz_bar"

[[addons]]
folder = "jazztronauts"
url = "https://github.com/Foohy/jazztronauts.git"
branch = "master"
gamemodes = ["jazztronauts"]

[[addons]] # Wowozela
id = 108170491
download = true
