title = "Half-Life 2 Co-op"

[server]
gamemode = "lambda"
map = "d1_trainstation_01"

[[addons]]
folder = "lambda/gamemodes/lambda"
url = "https://github.com/GMLambda/Lambda.git"
branch = "develop"
gamemodes = ["lambda"]
