title = "Monster Mash"

[server]
gamemode = "monstermash"
map = "gm_construct"
host_workshop_collection = "3617554051"

[[collections]]
id = "3617554051"
title = "Gamestruct - Monster Mash"
description = "Server content for Gamestruct."

[[collections.items]]
id = "1541525700" # Monster Mash

[[collections.items]]
id = "1528995135"
maps = ["mm_harvest"]

[[collections.items]]
id = "1538691772"
maps = ["mm_village"]

[[collections.items]]
id = "1892856292"
maps = ["mm_swamp"]

[[collections.items]]
id = "2245065453"
maps = ["mm_rot"]

[[collections.items]]
id = "3054101759"
maps = ["mm_excrescentia"]

[[collections.items]]
id = "3596629218"
maps = ["mm_trickery"]

[[collections.items]]
id = "2977785840" # Clientside Hitreg
