title = "Monster Mash"

[server]
gamemode = "monstermash"
host_workshop_collection = 3617554051

[[addons]]
id = 1541525700 # Monster Mash

[[addons]]
id = 1528995135
maps = ["mm_harvest_v1", "mm_harvest_night"]

[[addons]]
id = 1538691772
maps = ["mm_village"]

[[addons]]
id = 1892856292
maps = ["mm_swamp"]

[[addons]]
id = 2245065453
maps = ["mm_rot"]

[[addons]]
id = 3054101759
maps = ["mm_excrescentia_final"]

[[addons]]
id = 3596629218
maps = ["mm_trickery_final"]

[[addons]]
id = 2977785840 # Clientside Hitreg
