title = "Quake III Arena"

[server]
gamemode = "q3ffa" # there is also q3tdm for team deathmatch

[[addons]]
id = 160207505 # Quake 3
maps = [
	"q3_bloodrun",
	"q3dm1",
	"q3dm17",
	"q3dm2",
	"q3dm3",
	"q3dm7_wip",
	"q3tourney3",
	"q3tourney4_wip",
	"q3tourney5_wip",
	"q3tourney6_wip",
	"q3tourney7",
]

[[addons]]
id = 1390687051
maps = ["q3dm6"]

[[addons]]
id = 3317013513 # Quake 2 Maps
maps = [
	"q2_base1",
	"q2dm1",
	"q2dm2",
]

[[addons]]
id = 2977785840 # Clientside Hitreg
