title = "Quake III Arena"

[server]
gamemode = "q3ffa"

[[addons]]
id = 160207505 # Quake 3
gamemodes = ["q3ffa", "q3tdm"]

[[addons]]
id = 1390687051 # q3dm6

[[addons]]
id = 3317013513 # Quake 2 Maps
