title = "Sacrifun"

[server]
gamemode = "sacrifun"
host_workshop_collection = "821019109"

[[addons]]
type = "github"
folder = "sacrifun"
url = "https://github.com/Zet0rz/Sacrifun.git"
branch = "master"

[[collections]]
id = "821019109"
title = "Gamestruct - Sacrifun"
description = "Server content for Gamestruct."
