title = "Sandbox"

[server]
gamemode = "sandbox"
map = "gm_buildstruct"
host_workshop_collection = 1234567890

[[addons]]
folder = "buildstruct-custom-content"
url = "https://github.com/Buildstruct/buildstruct-custom-content.git"
branch = "main"

[[addons]]
folder = "wire"
url = "https://github.com/Buildstruct/wire.git"
branch = "master"

[[addons]]
folder = "starfallex"
url = "https://github.com/Buildstruct/StarfallEx.git"
branch = "master"

[[addons]]
folder = "pac3"
url = "https://github.com/Buildstruct/pac3.git"
branch = "develop"

[[addons]]
folder = "acf3"
url = "https://github.com/Buildstruct/ACF-3.git"
branch = "master"

[[addons]]
folder = "acf3missiles"
url = "https://github.com/Buildstruct/ACF-3-Missiles.git"
branch = "master"
