title = "Serious Sam Deathmatch"

[server]
gamemode = "serioussam_dm"

[[addons]]
id = 3127352943 # Serious Sam Deathmatch
gamemodes = ["serioussam_dm", "serioussam_tdm"]

[[addons]]
id = 258523980 # Serious Sam SWEPs
download = true

[[addons]]
id = 718492479 # Serious Sam Pickup Entities
download = true

[[addons]]
id = 262062192 # Serious Sam Playermodels
download = true
