title = "SlashCo"

[server]
gamemode = "slashco"
map = "sc_lobby"

[[addons]]
folder = "slashco"
url = "https://github.com/Mantibro/SlashCo.git"
branch = "beta"
gamemodes = ["slashco"]
maps = ["sc_lobby"]

[[addons]]
id = 2844081496
maps = ["sc_summercamp"]

[[addons]]
id = 2844082996
maps = ["sc_highschool"]

[[addons]]
id = 2856197297
maps = ["sc_hospital"]

[[addons]]
id = 2954492599
maps = ["sc_redforest"]

[[addons]]
id = 2981462975
maps = ["sc_asylum"]

[[addons]]
id = 3276058547
maps = ["sc_trainingcenter"]

[[addons]]
id = 3296523451
maps = ["sc_deadcity"]

[[addons]]
id = 3327358109
maps = ["sc_downtown_v2"]

[[addons]]
id = 3432479487
maps = ["sc_insertion2"]

[[addons]]
id = 2977785840 # Clientside Hitreg
