title = "Trouble in Terrorist Town"

[server]
gamemode = "terrortown" # already included with garrysmod

### maps ###

[[addons]]
id = 159321088
maps = ["ttt_minecraft_b5"]

[[addons]]
id = 157420728
maps = ["ttt_waterworld"]

[[addons]]
id = 106498411
maps = ["ttt_mc_skyislands"]

[[addons]]
id = 281454209
maps = ["ttt_clue_se"]

[[addons]]
id = 295897079
maps = ["ttt_lego"]

[[addons]]
id = 253297309
maps = ["ttt_airbus_b3"]

[[addons]]
id = 534491717
maps = ["ttt_rooftops_2016_v1"]

[[addons]]
id = 186842624
maps = ["ttt_minecraftcity_v4"]

[[addons]]
id = 131667838
maps = ["ttt_community_bowling_v5a"]

[[addons]]
id = 183797802
maps = ["ttt_island_2013"]

[[addons]]
id = 867635838
maps = ["ttt_grovestreet_a13"]

[[addons]]
id = 253328815
maps = ["ttt_skyscraper"]

[[addons]]
id = 2472169279
maps = ["ttt_airship_toppat"]

[[addons]]
id = 1475589106
maps = ["ttt_bikinibottom"]

[[addons]]
id = 624717817
maps = ["ttt_pcworld95"]

### extras ###

[[addons]]
folder = "swcs"
url = "https://gitlab.com/cynhole/swcs.git"
branch = "master"

[[addons]]
id = 151583504 # MapVote

[[addons]]
id = 1517464837 # Cigarette
download = true

[[addons]]
id = 645663146 # Sandwich (Medkit)
download = true

[[addons]]
id = 253737047 # Golden Deagle
download = true

[[addons]]
id = 643230441 # Mine Turtle (Proximity Mine)
download = true

[[addons]]
id = 254177306 # M4 SLAM (Tripmine + Remote C4)
download = true

[[addons]]
id = 254177214 # Jihad Bomb (Charred Corpse)
download = true

[[addons]]
id = 922342968 # Banana Bomb
download = true

[[addons]]
id = 3021464449 # Glue Trap
download = true

[[addons]]
id = 648957314 # Homerun Bat
download = true

[[addons]]
id = 3074845055 # Dead Ringer
download = true

[[addons]]
id = 294564108 # Explosive Melon Launcher
download = true

[[addons]]
id = 712675840 # Bomb Station
download = true

[[addons]]
id = 896084374 # The T-Suitcase
download = true

[[addons]]
id = 2150978792 # Paper Plane
download = true
