title = "The Lobby"

[server]
gamemode = "thelobby"
map = "gm_construct"

[[addons]]
folder = "gamestruct"
url = "https://github.com/Buildstruct/gamestruct.git"
branch = "main"
gamemodes = ["thelobby"]
