title = "Tobey Maguire's Pizza Delivery Deathmatch"

[server]
gamemode = "tmpddm"
map = "gm_bigcity"

[[addons]]
folder = "tmpddm/gamemodes/tmpddm"
url = "https://github.com/TomatoCo/tmpddm.git"
branch = "master"

[[addons]]
id = 105982362
maps = ["gm_bigcity"]

[[addons]]
id = 2977785840 # Clientside Hitreg
