title = "Zombie Survival"

[server]
gamemode = "zombiesurvival"

[[addons]]
folder = "zombiesurvival/gamemodes/zombiesurvival"
url = "https://github.com/Xalalau/Zombie-Survival-v1.11-Fix.git"
branch = "main"

[[addons]]
id = 3278214930 # ZS v1.11 Map Pack
download = true

[[addons]]
id = 3278214014 # ZS v1.11 CSS Weapons Replacement
download = true

[[addons]]
id = 3285251001 # ZS v1.11 Mapvote
